version: '3.7'
services:
  mongo:
    image: mongo:4.2
    environment: 
      - MONGODB_PASSWORD=uin-dev-2020
    volumes:
      - ./:/mongo-sh
    working_dir: /mongo-sh
    entrypoint: [ "sleep", "9999" ]

